
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/mingw64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 6.2.9200 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/mingw64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/mingw64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/mingw64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.0.0+c9eb9dd64
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2023/4/15 15:05:58。
      节点 1 上的项目“C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        E:\\Visual Studio\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        E:\\Visual Studio\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=E:\\Visual Studio\\VC\\Tools\\MSVC\\14.30.30705\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.77
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/3.26.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/mingw64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/mingw64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/mingw64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.0.0+c9eb9dd64
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2023/4/15 15:05:59。
      节点 1 上的项目“C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        E:\\Visual Studio\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        E:\\Visual Studio\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=E:\\Visual Studio\\VC\\Tools\\MSVC\\14.30.30705\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.54
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/3.26.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/mingw64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/mingw64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/CMakeScratch/TryCompile-9grke4"
      binary: "C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/CMakeScratch/TryCompile-9grke4"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/CMakeScratch/TryCompile-9grke4
        
        Run Build Command(s):E:/Visual Studio/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_ec9e5.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.0.0+c9eb9dd64
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2023/4/15 15:06:00。
        节点 1 上的项目“C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\CMakeScratch\\TryCompile-9grke4\\cmTC_ec9e5.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_ec9e5.dir\\Debug\\”。
          正在创建目录“C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\CMakeScratch\\TryCompile-9grke4\\Debug\\”。
          正在创建目录“cmTC_ec9e5.dir\\Debug\\cmTC_ec9e5.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_ec9e5.dir\\Debug\\cmTC_ec9e5.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          E:\\Visual Studio\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_ec9e5.dir\\Debug\\\\" /Fd"cmTC_ec9e5.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\mingw64\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.30.30712 版
          CMakeCCompilerABI.c
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_ec9e5.dir\\Debug\\\\" /Fd"cmTC_ec9e5.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\mingw64\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          E:\\Visual Studio\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\CMakeScratch\\TryCompile-9grke4\\Debug\\cmTC_ec9e5.exe" /INCREMENTAL /ILK:"cmTC_ec9e5.dir\\Debug\\cmTC_ec9e5.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/CMakeScratch/TryCompile-9grke4/Debug/cmTC_ec9e5.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/CMakeScratch/TryCompile-9grke4/Debug/cmTC_ec9e5.lib" /MACHINE:X64  /machine:x64 cmTC_ec9e5.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_ec9e5.vcxproj -> C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\CMakeScratch\\TryCompile-9grke4\\Debug\\cmTC_ec9e5.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_ec9e5.dir\\Debug\\cmTC_ec9e5.tlog\\unsuccessfulbuild”。
          正在对“cmTC_ec9e5.dir\\Debug\\cmTC_ec9e5.tlog\\cmTC_ec9e5.lastbuildstate”执行 Touch 任务。
        已完成生成项目“C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\CMakeScratch\\TryCompile-9grke4\\cmTC_ec9e5.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.54
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/mingw64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/mingw64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/CMakeScratch/TryCompile-og81bz"
      binary: "C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/CMakeScratch/TryCompile-og81bz"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/CMakeScratch/TryCompile-og81bz
        
        Run Build Command(s):E:/Visual Studio/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_3bf0c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.0.0+c9eb9dd64
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2023/4/15 15:06:01。
        节点 1 上的项目“C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\CMakeScratch\\TryCompile-og81bz\\cmTC_3bf0c.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_3bf0c.dir\\Debug\\”。
          正在创建目录“C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\CMakeScratch\\TryCompile-og81bz\\Debug\\”。
          正在创建目录“cmTC_3bf0c.dir\\Debug\\cmTC_3bf0c.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_3bf0c.dir\\Debug\\cmTC_3bf0c.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          E:\\Visual Studio\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_3bf0c.dir\\Debug\\\\" /Fd"cmTC_3bf0c.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\mingw64\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.30.30712 版
          CMakeCXXCompilerABI.cpp
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_3bf0c.dir\\Debug\\\\" /Fd"cmTC_3bf0c.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\mingw64\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          E:\\Visual Studio\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\CMakeScratch\\TryCompile-og81bz\\Debug\\cmTC_3bf0c.exe" /INCREMENTAL /ILK:"cmTC_3bf0c.dir\\Debug\\cmTC_3bf0c.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/CMakeScratch/TryCompile-og81bz/Debug/cmTC_3bf0c.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Angus Wang/Desktop/project-3/src/CMakeFiles/CMakeScratch/TryCompile-og81bz/Debug/cmTC_3bf0c.lib" /MACHINE:X64  /machine:x64 cmTC_3bf0c.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_3bf0c.vcxproj -> C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\CMakeScratch\\TryCompile-og81bz\\Debug\\cmTC_3bf0c.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_3bf0c.dir\\Debug\\cmTC_3bf0c.tlog\\unsuccessfulbuild”。
          正在对“cmTC_3bf0c.dir\\Debug\\cmTC_3bf0c.tlog\\cmTC_3bf0c.lastbuildstate”执行 Touch 任务。
        已完成生成项目“C:\\Users\\Angus Wang\\Desktop\\project-3\\src\\CMakeFiles\\CMakeScratch\\TryCompile-og81bz\\cmTC_3bf0c.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.58
        
      exitCode: 0
...
